### ISSUE TITLE
Sorry for disturbing

### ISSUE THREAD

**Issue by dongwu92** [dneprDroid/ImageRecognizer-iOS#1]
One more question. Could you please compress the folder `amalgamation` and the file `config.mk` in you mxnet root, and attach it here. I want to make a comparison with mine to find the problem.
Thank you very much!

**Comment by dongwu92** [comment]
I also clone the upgrade_mxnet branch and find 
`mxnet_predict-all.cc:11716:3: Unknown type name '__m128'`
Have you ever encounter this kind of problem?

**Comment by dneprDroid** [comment]
Did you change c++ compiler settings?
Check it:
<img width="760" alt="screen shot 2017-01-28 at 1 21 46 pm" src="https://cloud.githubusercontent.com/assets/13742733/22396251/0106c6de-e55d-11e6-855c-a4c71115ba06.png">


Because **__m128** defined in **xmmintrin.h** .

**Comment by dneprDroid** [comment]
config.mk and amalgamation folder: 
https://drive.google.com/open?id=0Bz6k8EQ1NzYMb0tLd1kyaEJreTg

**Comment by dongwu92** [comment]
Thank you very much!
